# Generated by Django 4.1.7 on 2023-03-24 21:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('General', '0001_initial'),
        ('Inventario', '0003_producto_operacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('rtn', models.CharField(blank=True, max_length=14, verbose_name='RTN')),
                ('paymentStatus', models.CharField(choices=[('0', 'Pendiente'), ('1', 'Pagado')], default='0', max_length=2, verbose_name='Estado de Pago')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.cliente', verbose_name='Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ElementoFactura',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finanzas.factura', verbose_name='Factura')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.producto', verbose_name='Producto')),
            ],
        ),
    ]
