# Generated by Django 4.1.7 on 2023-03-16 22:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('rtn', models.CharField(max_length=14)),
                ('name', models.CharField(max_length=150)),
                ('city', models.CharField(choices=[('1801', 'Yoro'), ('1806', 'Morazán'), ('1805', 'Jocón')], max_length=4)),
                ('address', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=70)),
                ('phone', models.CharField(max_length=8)),
                ('status', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
