# Generated by Django 4.1.7 on 2023-03-23 00:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0002_alter_proveedor_address_alter_proveedor_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('price', models.IntegerField(verbose_name='Precio')),
                ('status', models.BooleanField(default=True, help_text='Seleccione el estado del proveedor', verbose_name='Estado')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.proveedor', verbose_name='Proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('description', models.CharField(help_text='Ingrese la descripcion', max_length=200, verbose_name='Descripcion')),
                ('quantity', models.IntegerField(help_text='Seleccione la cantidad de la operacion', verbose_name='Cantidad')),
                ('type', models.CharField(choices=[('1', 'Agregar'), ('0', 'Eliminar')], help_text='Ingrese el tipo de operacion', max_length=2, verbose_name='Tipo')),
                ('status', models.BooleanField(default=True, help_text='Seleccione el estado del proveedor', verbose_name='Estado')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.producto', verbose_name='Producto')),
            ],
        ),
    ]
